options:
  default_port:
    default: 27017
    type: string
    description: Default MongoDB port
  replicaset:
    default: myset
    type: string
    description: Name of the replica set
  web_admin_ui:
    default: yes
    type: string
    description: Replica Set Admin UI ( yes / no )
  replicaset_master:
    default: auto
    type: string
    description: Replica Set master ( optional ). Possible values are 'auto' for automatic detection based on install time or 'host:port' to connect to 'host' on 'port' and register as a member.
